// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	shareFieldNames          = builder.RawFieldNames(&Share{})
	shareRows                = strings.Join(shareFieldNames, ",")
	shareRowsExpectAutoSet   = strings.Join(stringx.Remove(shareFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	shareRowsWithPlaceHolder = strings.Join(stringx.Remove(shareFieldNames, "`ShareId`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheShareShareIdPrefix = "cache:share:shareId:"
)

type (
	shareModel interface {
		Insert(ctx context.Context, data *Share) (sql.Result, error)
		FindOne(ctx context.Context, shareId string) (*Share, error)
		Update(ctx context.Context, data *Share) error
		Delete(ctx context.Context, shareId string) error
	}

	defaultShareModel struct {
		sqlc.CachedConn
		table string
	}

	Share struct {
		ShareId  string         `db:"ShareId"`
		FilePath string         `db:"FilePath"`
		File     string         `db:"File"`
		FileType string         `db:"FileType"`
		FileSize float64        `db:"FileSize"`
		Password sql.NullString `db:"Password"`
		UserName string         `db:"UserName"`
	}
)

func newShareModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultShareModel {
	return &defaultShareModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`Share`",
	}
}

func (m *defaultShareModel) Delete(ctx context.Context, shareId string) error {
	shareShareIdKey := fmt.Sprintf("%s%v", cacheShareShareIdPrefix, shareId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `ShareId` = ?", m.table)
		return conn.ExecCtx(ctx, query, shareId)
	}, shareShareIdKey)
	return err
}

func (m *defaultShareModel) FindOne(ctx context.Context, shareId string) (*Share, error) {
	shareShareIdKey := fmt.Sprintf("%s%v", cacheShareShareIdPrefix, shareId)
	var resp Share
	err := m.QueryRowCtx(ctx, &resp, shareShareIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `ShareId` = ? limit 1", shareRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, shareId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultShareModel) Insert(ctx context.Context, data *Share) (sql.Result, error) {
	shareShareIdKey := fmt.Sprintf("%s%v", cacheShareShareIdPrefix, data.ShareId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, shareRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ShareId, data.FilePath, data.File, data.FileType, data.FileSize, data.Password, data.UserName)
	}, shareShareIdKey)
	return ret, err
}

func (m *defaultShareModel) Update(ctx context.Context, data *Share) error {
	shareShareIdKey := fmt.Sprintf("%s%v", cacheShareShareIdPrefix, data.ShareId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `ShareId` = ?", m.table, shareRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.FilePath, data.File, data.FileType, data.FileSize, data.Password, data.UserName, data.ShareId)
	}, shareShareIdKey)
	return err
}

func (m *defaultShareModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheShareShareIdPrefix, primary)
}

func (m *defaultShareModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `ShareId` = ? limit 1", shareRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultShareModel) tableName() string {
	return m.table
}
