// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"BaiCloud/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: loginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/Refresh",
				Handler: RefreshHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/File/detail",
				Handler: FileHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/Photo/detail",
				Handler: PhotoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/Video/detail",
				Handler: VideoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/File/Data",
				Handler: FileDataHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: registerHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/verifyCode",
				Handler: verifyCodeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/File/Delete",
				Handler: FileDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/Dir/Create",
				Handler: CreateDirHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/Share/Create",
				Handler: CreateShareHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/Share/Delete",
				Handler: DeleteShareHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/Uplead/CreateFile",
				Handler: CreateUpleadFileHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/Uplead/File",
				Handler: UpleadFileHandler(serverCtx),
			},
		},
	)
}
